apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-service
  labels:
    app: aws-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-service
  template:
    metadata:
      labels:
        app: aws-service
    spec:
      containers:
        - name: aws-service
          image: ecioptime1231/aws-service:latest  # Replace with your Docker image
          imagePullPolicy: Always   # <-- Add this line
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: aws-service-service
spec:
  selector:
    app: aws-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
