apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-service
  labels:
    app: azure-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-service
  template:
    metadata:
      labels:
        app: azure-service
    spec:
      containers:
        - name: azure-service
          image: ecioptime1231/azure-service:latest  # Replace with your Docker image
          imagePullPolicy: Always   # <-- Add this line
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: azure-service-service
spec:
  selector:
    app: azure-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
