apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service
  labels:
    app: k8s-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service
  template:
    metadata:
      labels:
        app: k8s-service
    spec:
      containers:
        - name: k8s-service
          image: ecioptime1231/k8s-service:latest  # Replace with your Docker image
          imagePullPolicy: Always   # <-- Add this line
          ports:
            - containerPort: 5000  # Exposed port inside the container, update if necessary

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-service-service
spec:
  selector:
    app: k8s-service
  ports:
    - protocol: TCP
      port: 3004   # The port exposed by the service within the cluster
      targetPort: 3004  # The port your container is listening on
      nodePort: 30004    # The port exposed on each node (ensure it's in the valid range)
  type: NodePort   # Expose service externally using NodePort
